from django.urls import path

from .views import (
    admin_dashboard,
    admin_item_edit,
    admin_item_list,
    admin_user_edit,
    admin_user_list,
    conversation_detail,
    conversation_list,
    item_delete,
    item_detail,
    item_edit,
    item_list,
    mark_all_notifications_read,
    mark_notification_read,
    notification_list,
    report_found_item,
    report_lost_item,
    review_claim,
    start_conversation,
    submit_claim,
)

urlpatterns = [
    path("", item_list, name="item_list"),
    path("dashboard/", admin_dashboard, name="admin_dashboard"),
    path("dashboard/items/", admin_item_list, name="admin_item_list"),
    path("dashboard/items/<int:pk>/edit/", admin_item_edit, name="admin_item_edit"),
    path("dashboard/users/", admin_user_list, name="admin_user_list"),
    path("dashboard/users/<int:pk>/edit/", admin_user_edit, name="admin_user_edit"),
    path("alerts/", notification_list, name="notification_list"),
    path("alerts/read-all/", mark_all_notifications_read, name="mark_all_notifications_read"),
    path("alerts/<int:pk>/read/", mark_notification_read, name="mark_notification_read"),
    path("messages/", conversation_list, name="conversation_list"),
    path("messages/<int:pk>/", conversation_detail, name="conversation_detail"),
    path("items/<int:pk>/", item_detail, name="item_detail"),
    path("items/<int:pk>/message/", start_conversation, name="start_conversation"),
    path("items/<int:pk>/claim/", submit_claim, name="submit_claim"),
    path("items/<int:pk>/edit/", item_edit, name="item_edit"),
    path("items/<int:pk>/delete/", item_delete, name="item_delete"),
    path("claims/<int:pk>/<str:decision>/", review_claim, name="review_claim"),
    path("items/lost/new/", report_lost_item, name="report_lost_item"),
    path("items/found/new/", report_found_item, name="report_found_item"),
]
