# Generated by Django 5.2.8 on 2026-05-03 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='identification_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Identification card or National ID card number'),
        ),
    ]
