# Generated by Django 5.2.8 on 2026-06-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_content_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='image_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='image_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
